package org.mifos.connector.gsmastub.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import org.springframework.validation.annotation.Validated;
import org.threeten.bp.OffsetDateTime;

/**
 * ResponseBillPayment2
 */
@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-09-27T11:46:46.417Z[GMT]")

public class ResponseBillPayment2 {

    @JsonProperty("serviceProviderPaymentReference")
    private String serviceProviderPaymentReference = null;

    @JsonProperty("requestingOrganisationTransactionReference")
    private String requestingOrganisationTransactionReference = null;

    @JsonProperty("customerReference")
    private String customerReference = null;

    @JsonProperty("paymentType")
    private PaymentType paymentType = null;

    @JsonProperty("billPaymentStatus")
    private String billPaymentStatus = null;

    @JsonProperty("amountPaid")
    private String amountPaid = null;

    @JsonProperty("currency")
    private Currency currency = null;

    @JsonProperty("requestingOrganisation")
    private String requestingOrganisation = null;

    @JsonProperty("serviceProviderComment")
    private String serviceProviderComment = null;

    @JsonProperty("serviceProviderNotification")
    private String serviceProviderNotification = null;

    @JsonProperty("requestDate")
    private OffsetDateTime requestDate = null;

    @JsonProperty("creationDate")
    private OffsetDateTime creationDate = null;

    @JsonProperty("modificationDate")
    private OffsetDateTime modificationDate = null;

    @JsonProperty("customData")
    private CustomDataArray customData = null;

    @JsonProperty("metadata")
    private MetadataArray metadata = null;

    @JsonProperty("paidAmount")
    private String paidAmount = null;

    public ResponseBillPayment2 serviceProviderPaymentReference(String serviceProviderPaymentReference) {
        this.serviceProviderPaymentReference = serviceProviderPaymentReference;
        return this;
    }

    /**
     * Reference for the payment generated by the service provider.
     *
     * @return serviceProviderPaymentReference
     **/
    @Schema(description = "Reference for the payment generated by the service provider.")

    @Size(max = 256)
    public String getServiceProviderPaymentReference() {
        return serviceProviderPaymentReference;
    }

    public void setServiceProviderPaymentReference(String serviceProviderPaymentReference) {
        this.serviceProviderPaymentReference = serviceProviderPaymentReference;
    }

    public ResponseBillPayment2 requestingOrganisationTransactionReference(String requestingOrganisationTransactionReference) {
        this.requestingOrganisationTransactionReference = requestingOrganisationTransactionReference;
        return this;
    }

    /**
     * A reference provided by the requesting organisation that is to be associated with the transaction.
     *
     * @return requestingOrganisationTransactionReference
     **/
    @Schema(description = "A reference provided by the requesting organisation that is to be associated with the transaction.")

    @Size(max = 256)
    public String getRequestingOrganisationTransactionReference() {
        return requestingOrganisationTransactionReference;
    }

    public void setRequestingOrganisationTransactionReference(String requestingOrganisationTransactionReference) {
        this.requestingOrganisationTransactionReference = requestingOrganisationTransactionReference;
    }

    public ResponseBillPayment2 customerReference(String customerReference) {
        this.customerReference = customerReference;
        return this;
    }

    /**
     * Textual reference provided by the customer paying the bill.
     *
     * @return customerReference
     **/
    @Schema(description = "Textual reference provided by the customer paying the bill.")

    @Size(max = 256)
    public String getCustomerReference() {
        return customerReference;
    }

    public void setCustomerReference(String customerReference) {
        this.customerReference = customerReference;
    }

    public ResponseBillPayment2 paymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
        return this;
    }

    /**
     * Get paymentType
     *
     * @return paymentType
     **/
    @Schema(description = "")

    @Valid
    public PaymentType getPaymentType() {
        return paymentType;
    }

    public void setPaymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
    }

    public ResponseBillPayment2 billPaymentStatus(String billPaymentStatus) {
        this.billPaymentStatus = billPaymentStatus;
        return this;
    }

    /**
     * Indicates the status of the bill payment as stored by the API provider.
     *
     * @return billPaymentStatus
     **/
    @Schema(required = true, description = "Indicates the status of the bill payment as stored by the API provider.")
    @NotNull

    @Size(max = 256)
    public String getBillPaymentStatus() {
        return billPaymentStatus;
    }

    public void setBillPaymentStatus(String billPaymentStatus) {
        this.billPaymentStatus = billPaymentStatus;
    }

    public ResponseBillPayment2 amountPaid(String amountPaid) {
        this.amountPaid = amountPaid;
        return this;
    }

    /**
     * Get amountPaid
     *
     * @return amountPaid
     **/
    @Schema(example = "15.21", required = true, description = "")
    @NotNull

    @Pattern(regexp = "^([0]|([1-9][0-9]{0,17}))([.][0-9]{0,3}[0-9])?$")
    @Size(min = 1, max = 23)
    public String getAmountPaid() {
        return amountPaid;
    }

    public void setAmountPaid(String amountPaid) {
        this.amountPaid = amountPaid;
    }

    public ResponseBillPayment2 currency(Currency currency) {
        this.currency = currency;
        return this;
    }

    /**
     * Get currency
     *
     * @return currency
     **/
    @Schema(required = true, description = "")
    @NotNull

    @Valid
    public Currency getCurrency() {
        return currency;
    }

    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

    public ResponseBillPayment2 requestingOrganisation(String requestingOrganisation) {
        this.requestingOrganisation = requestingOrganisation;
        return this;
    }

    /**
     * The originating mobile money provider or financial institution that holds the wallet/account of the payer.
     *
     * @return requestingOrganisation
     **/
    @Schema(description = "The originating mobile money provider or financial institution that holds the wallet/account of the payer.")

    @Size(max = 256)
    public String getRequestingOrganisation() {
        return requestingOrganisation;
    }

    public void setRequestingOrganisation(String requestingOrganisation) {
        this.requestingOrganisation = requestingOrganisation;
    }

    public ResponseBillPayment2 serviceProviderComment(String serviceProviderComment) {
        this.serviceProviderComment = serviceProviderComment;
        return this;
    }

    /**
     * Allows the Service Provider to include specific information regarding the bill payment.
     *
     * @return serviceProviderComment
     **/
    @Schema(description = "Allows the Service Provider to include specific information regarding the bill payment.")

    @Size(max = 256)
    public String getServiceProviderComment() {
        return serviceProviderComment;
    }

    public void setServiceProviderComment(String serviceProviderComment) {
        this.serviceProviderComment = serviceProviderComment;
    }

    public ResponseBillPayment2 serviceProviderNotification(String serviceProviderNotification) {
        this.serviceProviderNotification = serviceProviderNotification;
        return this;
    }

    /**
     * Allows the Service Provider to include specific information that will be included on the notification to the
     * customer by the mobile money provider.
     *
     * @return serviceProviderNotification
     **/
    @Schema(description = "Allows the Service Provider to include specific information that will be included on the notification to the customer by the mobile money provider.")

    @Size(max = 256)
    public String getServiceProviderNotification() {
        return serviceProviderNotification;
    }

    public void setServiceProviderNotification(String serviceProviderNotification) {
        this.serviceProviderNotification = serviceProviderNotification;
    }

    public ResponseBillPayment2 requestDate(OffsetDateTime requestDate) {
        this.requestDate = requestDate;
        return this;
    }

    /**
     * The date and time of the request as supplied by the client.
     *
     * @return requestDate
     **/
    @Schema(description = "The date and time of the request as supplied by the client.")

    @Valid
    public OffsetDateTime getRequestDate() {
        return requestDate;
    }

    public void setRequestDate(OffsetDateTime requestDate) {
        this.requestDate = requestDate;
    }

    public ResponseBillPayment2 creationDate(OffsetDateTime creationDate) {
        this.creationDate = creationDate;
        return this;
    }

    /**
     * Date and time when the object was created by the API Provider.
     *
     * @return creationDate
     **/
    @Schema(description = "Date and time when the object was created by the API Provider.")

    @Valid
    public OffsetDateTime getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(OffsetDateTime creationDate) {
        this.creationDate = creationDate;
    }

    public ResponseBillPayment2 modificationDate(OffsetDateTime modificationDate) {
        this.modificationDate = modificationDate;
        return this;
    }

    /**
     * Date and time when the object was modified by the API Provider.
     *
     * @return modificationDate
     **/
    @Schema(description = "Date and time when the object was modified by the API Provider.")

    @Valid
    public OffsetDateTime getModificationDate() {
        return modificationDate;
    }

    public void setModificationDate(OffsetDateTime modificationDate) {
        this.modificationDate = modificationDate;
    }

    public ResponseBillPayment2 customData(CustomDataArray customData) {
        this.customData = customData;
        return this;
    }

    /**
     * Get customData
     *
     * @return customData
     **/
    @Schema(description = "")

    @Valid
    public CustomDataArray getCustomData() {
        return customData;
    }

    public void setCustomData(CustomDataArray customData) {
        this.customData = customData;
    }

    public ResponseBillPayment2 metadata(MetadataArray metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get metadata
     *
     * @return metadata
     **/
    @Schema(description = "")

    @Valid
    public MetadataArray getMetadata() {
        return metadata;
    }

    public void setMetadata(MetadataArray metadata) {
        this.metadata = metadata;
    }

    public ResponseBillPayment2 paidAmount(String paidAmount) {
        this.paidAmount = paidAmount;
        return this;
    }

    /**
     * Get paidAmount
     *
     * @return paidAmount
     **/
    @Schema(example = "15.21", description = "")

    @Pattern(regexp = "^([0]|([1-9][0-9]{0,17}))([.][0-9]{0,3}[0-9])?$")
    @Size(min = 1, max = 23)
    public String getPaidAmount() {
        return paidAmount;
    }

    public void setPaidAmount(String paidAmount) {
        this.paidAmount = paidAmount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResponseBillPayment2 responseBillPayment2 = (ResponseBillPayment2) o;
        return Objects.equals(this.serviceProviderPaymentReference, responseBillPayment2.serviceProviderPaymentReference)
                && Objects.equals(this.requestingOrganisationTransactionReference,
                        responseBillPayment2.requestingOrganisationTransactionReference)
                && Objects.equals(this.customerReference, responseBillPayment2.customerReference)
                && Objects.equals(this.paymentType, responseBillPayment2.paymentType)
                && Objects.equals(this.billPaymentStatus, responseBillPayment2.billPaymentStatus)
                && Objects.equals(this.amountPaid, responseBillPayment2.amountPaid)
                && Objects.equals(this.currency, responseBillPayment2.currency)
                && Objects.equals(this.requestingOrganisation, responseBillPayment2.requestingOrganisation)
                && Objects.equals(this.serviceProviderComment, responseBillPayment2.serviceProviderComment)
                && Objects.equals(this.serviceProviderNotification, responseBillPayment2.serviceProviderNotification)
                && Objects.equals(this.requestDate, responseBillPayment2.requestDate)
                && Objects.equals(this.creationDate, responseBillPayment2.creationDate)
                && Objects.equals(this.modificationDate, responseBillPayment2.modificationDate)
                && Objects.equals(this.customData, responseBillPayment2.customData)
                && Objects.equals(this.metadata, responseBillPayment2.metadata)
                && Objects.equals(this.paidAmount, responseBillPayment2.paidAmount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(serviceProviderPaymentReference, requestingOrganisationTransactionReference, customerReference, paymentType,
                billPaymentStatus, amountPaid, currency, requestingOrganisation, serviceProviderComment, serviceProviderNotification,
                requestDate, creationDate, modificationDate, customData, metadata, paidAmount);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ResponseBillPayment2 {\n");

        sb.append("    serviceProviderPaymentReference: ").append(toIndentedString(serviceProviderPaymentReference)).append("\n");
        sb.append("    requestingOrganisationTransactionReference: ").append(toIndentedString(requestingOrganisationTransactionReference))
                .append("\n");
        sb.append("    customerReference: ").append(toIndentedString(customerReference)).append("\n");
        sb.append("    paymentType: ").append(toIndentedString(paymentType)).append("\n");
        sb.append("    billPaymentStatus: ").append(toIndentedString(billPaymentStatus)).append("\n");
        sb.append("    amountPaid: ").append(toIndentedString(amountPaid)).append("\n");
        sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
        sb.append("    requestingOrganisation: ").append(toIndentedString(requestingOrganisation)).append("\n");
        sb.append("    serviceProviderComment: ").append(toIndentedString(serviceProviderComment)).append("\n");
        sb.append("    serviceProviderNotification: ").append(toIndentedString(serviceProviderNotification)).append("\n");
        sb.append("    requestDate: ").append(toIndentedString(requestDate)).append("\n");
        sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
        sb.append("    modificationDate: ").append(toIndentedString(modificationDate)).append("\n");
        sb.append("    customData: ").append(toIndentedString(customData)).append("\n");
        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("    paidAmount: ").append(toIndentedString(paidAmount)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
